name: mustache
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_0
  - openssl=1.1.1d=h7b6447c_4
  - pip=20.0.2=py38_1
  - python=3.8.1=h0371630_1
  - readline=7.0=h7b6447c_5
  - setuptools=45.2.0=py38_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
      - asciitree==0.3.3
      - biopython==1.76
      - chardet==3.0.4
      - click==7.0
      - cooler==0.8.7
      - cycler==0.10.0
      - cytoolz==0.10.1
      - dill==0.3.1.1
      - h5py==2.10.0
      - hic-straw==0.0.6
      - idna==2.9
      - kiwisolver==1.1.0
      - matplotlib==3.1.3
      - multiprocess==0.70.9
      - mustache-hic>=0.1.10
      - numpy==1.18.1
      - pandas==1.0.1
      - pathlib==1.0.1
      - patsy==0.5.1
      - pyfaidx==0.5.8
      - pypairix==0.3.7
      - pyparsing==2.4.6
      - pysam==0.15.4
      - python-dateutil==2.8.1
      - pytz==2019.3
      - pyyaml==5.3
      - requests==2.23.0
      - scipy==1.4.1
      - simplejson==3.17.0
      - six==1.14.0
      - statsmodels==0.11.1
      - toolz==0.10.0
      - urllib3==1.25.8
