name: mustache
channels:
  - conda-forge
  - defaults

  - libedit==3.1.20181209=hc058e9b_0
  - zlib==1.2.11=h7b6447c_3
  - python==3.8.1=h0371630_1
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - wheel==0.34.2=py38_0
  - readline==7.0=h7b6447c_5
  - ncurses==6.2=he6710b0_0
  - tk==8.6.8=hbc83047_0
  - pip==20.0.2=py38_1
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - certifi==2019.11.28=py38_0
  - libffi==3.2.1=hd88cf55_4
  - xz==5.2.4=h14c3975_4
  - openssl==1.1.1d=h7b6447c_4
  - setuptools==45.2.0=py38_0
  - sqlite==3.31.1=h7b6447c_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - ca-certificates==2020.1.1=0
  - _libgcc_mutex==0.1=main
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_0
  - openssl=1.1.1d=h7b6447c_4
  - pip=20.0.2=py38_1
  - python=3.8.1=h0371630_1
  - readline=7.0=h7b6447c_5
  - setuptools=45.2.0=py38_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - asciitree==0.3.3
    - biopython==1.76
    - bleach==4.1.0
    - cffi==1.15.0
    - chardet==3.0.4
    - click==7.0
    - colorama==0.4.4
    - cooler==0.8.7
    - cryptography==35.0.0
    - cycler==0.10.0
    - cytoolz==0.10.1
    - dill==0.3.1.1
    - docutils==0.18
    - h5py==2.10.0
    - hic-straw==1.3.0
    - idna==2.9
    - importlib-metadata==4.8.1
    - jeepney==0.7.1
    - keyring==23.2.1
    - kiwisolver==1.1.0
    - matplotlib==3.1.3
    - multiprocess==0.70.9
    - mustache-hic==0.1.9
    - numpy==1.18.1
    - packaging==21.0
    - pandas==1.0.1
    - pathlib==1.0.1
    - patsy==0.5.1
    - pkginfo==1.7.1
    - pybind11==2.8.1
    - pycparser==2.20
    - pyfaidx==0.5.8
    - pygments==2.10.0
    - pypairix==0.3.7
    - pyparsing==2.4.6
    - pysam==0.15.4
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyyaml==5.3
    - readme-renderer==30.0
    - requests==2.23.0
    - requests-toolbelt==0.9.1
    - rfc3986==1.5.0
    - scipy==1.4.1
    - secretstorage==3.3.1
    - simplejson==3.17.0
    - six==1.14.0
    - statsmodels==0.11.1
    - toolz==0.10.0
    - tqdm==4.62.3
    - twine==3.4.2
    - urllib3==1.25.8
    - webencodings==0.5.1
    - zipp==3.6.0
prefix: /home/abbas/miniconda3/envs/mustache
